// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ETE.Models;

public partial class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Codes> Codes { get; set; }

    public virtual DbSet<DeadTimes> DeadTimes { get; set; }

    public virtual DbSet<Hours> Hours { get; set; }

    public virtual DbSet<Lines> Lines { get; set; }

    public virtual DbSet<Machine> Machine { get; set; }

    public virtual DbSet<Process> Process { get; set; }

    public virtual DbSet<Production> Production { get; set; }

    public virtual DbSet<Reason> Reason { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Codes>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Codes__3214EC077B49E85A");

            entity.Property(e => e.Name)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasColumnName("name");
        });

        modelBuilder.Entity<DeadTimes>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DeadTime__3214EC0713927D25");

            entity.Property(e => e.CodeId).HasColumnName("codeId");
            entity.Property(e => e.Minutes).HasColumnName("minutes");
            entity.Property(e => e.ReasonId).HasColumnName("reasonId");

            entity.HasOne(d => d.Code).WithMany(p => p.DeadTimes)
                .HasForeignKey(d => d.CodeId)
                .HasConstraintName("FK__DeadTimes__codeI__628FA481");

            entity.HasOne(d => d.Reason).WithMany(p => p.DeadTimes)
                .HasForeignKey(d => d.ReasonId)
                .HasConstraintName("FK__DeadTimes__reaso__6383C8BA");
        });

        modelBuilder.Entity<Hours>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Hours__3214EC078CDB5ADA");

            entity.Property(e => e.Time)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("time");
        });

        modelBuilder.Entity<Lines>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Lines__3214EC07AB067F1D");

            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("name");
        });

        modelBuilder.Entity<Machine>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Machine__3214EC07BE30DECD");

            entity.Property(e => e.Name)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasColumnName("name");
            entity.Property(e => e.ProcessId).HasColumnName("processId");

            entity.HasOne(d => d.Process).WithMany(p => p.Machine)
                .HasForeignKey(d => d.ProcessId)
                .HasConstraintName("FK__Machine__process__403A8C7D");
        });

        modelBuilder.Entity<Process>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Process__3214EC07D2509706");

            entity.Property(e => e.LineId).HasColumnName("lineId");
            entity.Property(e => e.Name)
                .HasMaxLength(70)
                .IsUnicode(false)
                .HasColumnName("name");

            entity.HasOne(d => d.Line).WithMany(p => p.Process)
                .HasForeignKey(d => d.LineId)
                .HasConstraintName("FK__Process__lineId__3D5E1FD2");
        });

        modelBuilder.Entity<Production>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Producti__3214EC07E2B970B4");

            entity.Property(e => e.DeadTimesId).HasColumnName("deadTimesId");
            entity.Property(e => e.HourId).HasColumnName("hourId");
            entity.Property(e => e.LinesId).HasColumnName("linesId");
            entity.Property(e => e.MachineId).HasColumnName("machineId");
            entity.Property(e => e.PartNumber)
                .HasMaxLength(80)
                .IsUnicode(false)
                .HasColumnName("partNumber");
            entity.Property(e => e.PieceQuantity).HasColumnName("pieceQuantity");
            entity.Property(e => e.ProcessId).HasColumnName("processId");

            entity.HasOne(d => d.DeadTimes).WithMany(p => p.Production)
                .HasForeignKey(d => d.DeadTimesId)
                .HasConstraintName("FK__Productio__deadT__6A30C649");

            entity.HasOne(d => d.Hour).WithMany(p => p.Production)
                .HasForeignKey(d => d.HourId)
                .HasConstraintName("FK__Productio__hourI__66603565");

            entity.HasOne(d => d.Lines).WithMany(p => p.Production)
                .HasForeignKey(d => d.LinesId)
                .HasConstraintName("FK__Productio__lines__6754599E");

            entity.HasOne(d => d.Machine).WithMany(p => p.Production)
                .HasForeignKey(d => d.MachineId)
                .HasConstraintName("FK__Productio__machi__693CA210");

            entity.HasOne(d => d.Process).WithMany(p => p.Production)
                .HasForeignKey(d => d.ProcessId)
                .HasConstraintName("FK__Productio__proce__68487DD7");
        });

        modelBuilder.Entity<Reason>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Reason__3214EC07909D2908");

            entity.Property(e => e.CodeId).HasColumnName("codeId");
            entity.Property(e => e.Name)
                .HasMaxLength(80)
                .IsUnicode(false)
                .HasColumnName("name");

            entity.HasOne(d => d.Code).WithMany(p => p.Reason)
                .HasForeignKey(d => d.CodeId)
                .HasConstraintName("FK__Reason__codeId__59063A47");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}