// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ETE.Models;

public partial class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Codes> Codes { get; set; }

    public virtual DbSet<DeadTimes> DeadTimes { get; set; }

    public virtual DbSet<Hours> Hours { get; set; }

    public virtual DbSet<Lines> Lines { get; set; }

    public virtual DbSet<Machine> Machine { get; set; }

    public virtual DbSet<MasterEngineering> MasterEngineering { get; set; }

    public virtual DbSet<Process> Process { get; set; }

    public virtual DbSet<Production> Production { get; set; }

    public virtual DbSet<Reason> Reason { get; set; }

    public virtual DbSet<WorkShift> WorkShift { get; set; }

    public virtual DbSet<WorkShiftHours> WorkShiftHours { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Codes>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Codes__3214EC077B49E85A");

            entity.Property(e => e.Name)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasColumnName("name");
        });

        modelBuilder.Entity<DeadTimes>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DeadTime__3214EC0713927D25");

            entity.Property(e => e.CodeId).HasColumnName("codeId");
            entity.Property(e => e.Minutes).HasColumnName("minutes");
            entity.Property(e => e.ReasonId).HasColumnName("reasonId");

            entity.HasOne(d => d.Code).WithMany(p => p.DeadTimes)
                .HasForeignKey(d => d.CodeId)
                .HasConstraintName("FK__DeadTimes__codeI__628FA481");

            entity.HasOne(d => d.Reason).WithMany(p => p.DeadTimes)
                .HasForeignKey(d => d.ReasonId)
                .HasConstraintName("FK__DeadTimes__reaso__6383C8BA");
        });

        modelBuilder.Entity<Hours>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Hours__3214EC073E7532DC");

            entity.Property(e => e.Date)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Time)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("time");
        });

        modelBuilder.Entity<Lines>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Lines__3214EC0727D090B8");

            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("name");
        });

        modelBuilder.Entity<Machine>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Machine__3214EC07F800F9FD");

            entity.Property(e => e.Name)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasColumnName("name");
            entity.Property(e => e.ProcessId).HasColumnName("processId");

            entity.HasOne(d => d.Process).WithMany(p => p.Machine)
                .HasForeignKey(d => d.ProcessId)
                .HasConstraintName("FK__Machine__process__71D1E811");
        });

        modelBuilder.Entity<MasterEngineering>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__MasterEn__3214EC074289B74F");

            entity.Property(e => e.ChildPartNumber)
                .HasMaxLength(70)
                .IsUnicode(false)
                .HasColumnName("childPartNumber");
            entity.Property(e => e.Ciclo)
                .HasColumnType("decimal(16, 10)")
                .HasColumnName("ciclo");
            entity.Property(e => e.Client)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("client");
            entity.Property(e => e.Concatenated)
                .HasMaxLength(70)
                .IsUnicode(false)
                .HasColumnName("concatenated");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("descripcion");
            entity.Property(e => e.Development)
                .HasColumnType("decimal(12, 4)")
                .HasColumnName("development");
            entity.Property(e => e.ExternalDiameter)
                .HasMaxLength(80)
                .IsUnicode(false)
                .HasColumnName("externalDiameter");
            entity.Property(e => e.Family)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasColumnName("family");
            entity.Property(e => e.Line).HasColumnName("line");
            entity.Property(e => e.Oper).HasColumnName("oper");
            entity.Property(e => e.OperSetup).HasColumnName("operSetup");
            entity.Property(e => e.Operation)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("operation");
            entity.Property(e => e.ParentPartNumber)
                .HasMaxLength(70)
                .IsUnicode(false)
                .HasColumnName("parentPartNumber");
            entity.Property(e => e.Process)
                .HasMaxLength(80)
                .IsUnicode(false)
                .HasColumnName("process");
            entity.Property(e => e.ProcessComments)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("processComments");
            entity.Property(e => e.PurchasePart)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("purchasePart");
            entity.Property(e => e.PzHr).HasColumnName("pzHr");
            entity.Property(e => e.QuantityXunit)
                .HasColumnType("decimal(12, 4)")
                .HasColumnName("quantityXUnit");
            entity.Property(e => e.Sequence).HasColumnName("sequence");
            entity.Property(e => e.TSetupMayor)
                .HasColumnType("decimal(12, 4)")
                .HasColumnName("tSetupMayor");
            entity.Property(e => e.TSetupMinor)
                .HasColumnType("decimal(12, 4)")
                .HasColumnName("tSetupMinor");
            entity.Property(e => e.Type)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("type");
            entity.Property(e => e.Verification)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("verification");
            entity.Property(e => e.WallThickness)
                .HasColumnType("decimal(12, 4)")
                .HasColumnName("wallThickness");
        });

        modelBuilder.Entity<Process>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Process__3214EC0733128B75");

            entity.Property(e => e.LineId).HasColumnName("lineId");
            entity.Property(e => e.Name)
                .HasMaxLength(70)
                .IsUnicode(false)
                .HasColumnName("name");

            entity.HasOne(d => d.Line).WithMany(p => p.Process)
                .HasForeignKey(d => d.LineId)
                .HasConstraintName("FK__Process__lineId__6EF57B66");
        });

        modelBuilder.Entity<Production>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Producti__3214EC07759FB59E");

            entity.Property(e => e.DeadTimesId).HasColumnName("deadTimesId");
            entity.Property(e => e.HourId).HasColumnName("hourId");
            entity.Property(e => e.LinesId).HasColumnName("linesId");
            entity.Property(e => e.MachineId).HasColumnName("machineId");
            entity.Property(e => e.MasterEnginnerId).HasColumnName("masterEnginnerId");
            entity.Property(e => e.PartNumber)
                .HasMaxLength(80)
                .IsUnicode(false)
                .HasColumnName("partNumber");
            entity.Property(e => e.PieceQuantity).HasColumnName("pieceQuantity");
            entity.Property(e => e.ProcessId).HasColumnName("processId");
            entity.Property(e => e.Scrap).HasColumnName("scrap");

            entity.HasOne(d => d.DeadTimes).WithMany(p => p.Production)
                .HasForeignKey(d => d.DeadTimesId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__Productio__deadT__160F4887");

            entity.HasOne(d => d.Hour).WithMany(p => p.Production)
                .HasForeignKey(d => d.HourId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__Productio__hourI__1332DBDC");

            entity.HasOne(d => d.Lines).WithMany(p => p.Production)
                .HasForeignKey(d => d.LinesId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__Productio__lines__14270015");

            entity.HasOne(d => d.MasterEnginner).WithMany(p => p.Production)
                .HasForeignKey(d => d.MasterEnginnerId)
                .HasConstraintName("FK__Productio__maste__1BC821DD");

            entity.HasOne(d => d.Process).WithMany(p => p.Production)
                .HasForeignKey(d => d.ProcessId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__Productio__proce__151B244E");
        });

        modelBuilder.Entity<Reason>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Reason__3214EC07909D2908");

            entity.Property(e => e.CodeId).HasColumnName("codeId");
            entity.Property(e => e.Name)
                .HasMaxLength(80)
                .IsUnicode(false)
                .HasColumnName("name");

            entity.HasOne(d => d.Code).WithMany(p => p.Reason)
                .HasForeignKey(d => d.CodeId)
                .HasConstraintName("FK__Reason__codeId__59063A47");
        });

        modelBuilder.Entity<WorkShift>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__WorkShif__3214EC0795F91C10");

            entity.Property(e => e.Name)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("name");
        });

        modelBuilder.Entity<WorkShiftHours>(entity =>
        {
            entity.HasKey(e => new { e.WorkShiftId, e.HourId }).HasName("PK__WorkShif__A8B003DC04E6EB75");

            entity.HasOne(d => d.Hour).WithMany(p => p.WorkShiftHours)
                .HasForeignKey(d => d.HourId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__WorkShift__HourI__19DFD96B");

            entity.HasOne(d => d.WorkShift).WithMany(p => p.WorkShiftHours)
                .HasForeignKey(d => d.WorkShiftId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__WorkShift__WorkS__18EBB532");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}