// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETE.Models;

public partial class Codes
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<DeadTimes> DeadTimes { get; set; } = new List<DeadTimes>();

    public virtual ICollection<Reason> Reason { get; set; } = new List<Reason>();
}