// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETE.Models;

public partial class DeadTimes
{
    public int Id { get; set; }

    public int? Minutes { get; set; }

    public int? CodeId { get; set; }

    public int? ReasonId { get; set; }

    public DateTime? RegistrationDate { get; set; }

    public virtual Codes Code { get; set; }

    public virtual ICollection<Production> Production { get; set; } = new List<Production>();

    public virtual Reason Reason { get; set; }
}