// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETE.Models;

public partial class Lines
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Process> Process { get; set; } = new List<Process>();

    public virtual ICollection<Production> Production { get; set; } = new List<Production>();
}