// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETE.Models;

public partial class Machine
{
    public int Id { get; set; }

    public int? ProcessId { get; set; }

    public string Name { get; set; }

    public virtual Process Process { get; set; }
}