// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETE.Models;

public partial class MasterEngineering
{
    public int Id { get; set; }

    public string ParentPartNumber { get; set; }

    public string ChildPartNumber { get; set; }

    public string Process { get; set; }

    public string Concatenated { get; set; }

    public string ExternalDiameter { get; set; }

    public string Descripcion { get; set; }

    public string Type { get; set; }

    public string Family { get; set; }

    public string Client { get; set; }

    public int? Line { get; set; }

    public string PurchasePart { get; set; }

    public string Operation { get; set; }

    public int? Sequence { get; set; }

    public string ProcessComments { get; set; }

    public int? OperSetup { get; set; }

    public int? Oper { get; set; }

    public int? PzHr { get; set; }

    public string Verification { get; set; }

    public virtual ICollection<Production> Production { get; set; } = new List<Production>();
}