// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETE.Models;

public partial class Process
{
    public int Id { get; set; }

    public int? LineId { get; set; }

    public string Name { get; set; }

    public virtual Lines Line { get; set; }

    public virtual ICollection<Machine> Machine { get; set; } = new List<Machine>();

    public virtual ICollection<Production> Production { get; set; } = new List<Production>();
}