// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETE.Models;

public partial class Production
{
    public int Id { get; set; }

    public string PartNumber { get; set; }

    public int? PieceQuantity { get; set; }

    public int HourId { get; set; }

    public int? LinesId { get; set; }

    public int? ProcessId { get; set; }

    public int? MachineId { get; set; }

    public int? DeadTimesId { get; set; }

    public int? MasterEnginnerId { get; set; }

    public int? Scrap { get; set; }

    public DateTime? RegistrationDate { get; set; }

    public DateTime? ManualDate { get; set; }

    public virtual DeadTimes DeadTimes { get; set; }

    public virtual Hours Hour { get; set; }

    public virtual Lines Lines { get; set; }

    public virtual MasterEngineering MasterEnginner { get; set; }

    public virtual Process Process { get; set; }
}