// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETE.Models;

public partial class Reason
{
    public int Id { get; set; }

    public int? CodeId { get; set; }

    public string Name { get; set; }

    public virtual Codes Code { get; set; }

    public virtual ICollection<DeadTimes> DeadTimes { get; set; } = new List<DeadTimes>();
}